# Generated by Django 3.2 on 2023-08-24 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TellerCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=100)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('mode_donation', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Draft', 'Draft'), ('Kind', 'Kind')], max_length=10)),
                ('amt_cash', models.PositiveSmallIntegerField(blank=True, max_length=6, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=6, null=True)),
                ('micr_cheque', models.CharField(blank=True, max_length=9, null=True)),
                ('draft_no', models.CharField(blank=True, max_length=6, null=True)),
                ('micr_draft', models.CharField(blank=True, max_length=9, null=True)),
                ('kind_type', models.CharField(blank=True, choices=[('Silver Like Material', 'Silver Like Material'), ('Gold Like Material', 'Gold Like Material'), ('Other', 'Other Valueble')], max_length=20, null=True)),
                ('kind_wgt', models.CharField(blank=True, max_length=4, null=True)),
                ('kind_unit', models.CharField(blank=True, choices=[('gram', 'gram'), ('kilogram', 'kilogram')], max_length=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellercounter.district')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellercounter.province')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distric_province', to='tellercounter.province'),
        ),
    ]
