# Generated by Django 3.2.7 on 2022-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TellerCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh\t', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli and Daman & Diu', 'Dadra & Nagar Haveli and Daman & Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry'), ('Ladakh', 'Ladakh')], max_length=50)),
                ('pin', models.CharField(default='NA', max_length=6)),
                ('mobile', models.CharField(default='NA', max_length=10)),
                ('mode_donation', models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Draft', 'Draft'), ('Kind', 'Kind')], default='Cash', max_length=10)),
                ('amt_cash', models.CharField(default='NA', max_length=6)),
                ('cheque_no', models.CharField(default='NA', max_length=6)),
                ('micr_cheque', models.CharField(default='NA', max_length=9)),
                ('draft_no', models.CharField(default='NA', max_length=6)),
                ('micr_draft', models.CharField(default='NA', max_length=9)),
                ('kind_type', models.CharField(choices=[('Silver Like Material', 'Silver Like Material'), ('Gold Like Material', 'Gold Like Material'), ('Other Valuable', 'Other Valueble')], default='NA', max_length=20)),
                ('kind_wgt', models.CharField(default='NA', max_length=4)),
                ('kind_unit', models.CharField(choices=[('gram', 'gram'), ('kilogram', 'kilogram')], default='NA', max_length=10)),
                ('comment', models.TextField(default='NA')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
