# Generated by Django 3.2.7 on 2022-01-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellercounter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellercounter',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
