# Generated by Django 3.2.7 on 2022-01-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellercounter', '0002_alter_tellercounter_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellercounter',
            name='amt_cash',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='draft_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='kind_type',
            field=models.CharField(blank=True, choices=[('Silver Like Material', 'Silver Like Material'), ('Gold Like Material', 'Gold Like Material'), ('Other Valuable', 'Other Valueble')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='kind_unit',
            field=models.CharField(blank=True, choices=[('gram', 'gram'), ('kilogram', 'kilogram')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='kind_wgt',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='micr_cheque',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='micr_draft',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='mode_donation',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Draft', 'Draft'), ('Kind', 'Kind')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tellercounter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
