# Generated by Django 3.2 on 2023-08-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellercounter', '0002_alter_tellercounter_amt_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tellercounter',
            name='address',
        ),
        migrations.AddField(
            model_name='tellercounter',
            name='amt_cheque',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tellercounter',
            name='amt_draft',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tellercounter',
            name='date_cheque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tellercounter',
            name='date_draft',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tellercounter',
            name='status',
            field=models.CharField(choices=[('live', 'live'), ('cancelled', 'cancelled')], default='live', max_length=9),
        ),
    ]
