# Generated by Django 3.2 on 2023-08-25 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tellercounter', '0003_auto_20230824_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellercounter',
            name='kind_type',
            field=models.CharField(blank=True, choices=[('Silver Like Material', 'Silver Like Material'), ('Gold Like Material', 'Gold Like Material'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='KindContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('mode_donation', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Draft', 'Draft'), ('Kind', 'Kind')], max_length=10)),
                ('kind_type', models.CharField(choices=[('Silver Like Material', 'Silver Like Material'), ('Gold Like Material', 'Gold Like Material'), ('Other', 'Other')], max_length=20)),
                ('kind_wgt', models.CharField(blank=True, max_length=4, null=True)),
                ('kind_unit', models.CharField(blank=True, choices=[('gram', 'gram'), ('kilogram', 'kilogram')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('live', 'live'), ('cancelled', 'cancelled')], default='live', max_length=9)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellercounter.district')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellercounter.province')),
            ],
        ),
        migrations.CreateModel(
            name='DraftContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('mode_donation', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Draft', 'Draft'), ('Kind', 'Kind')], max_length=10)),
                ('draft_no', models.CharField(max_length=6)),
                ('micr_draft', models.CharField(max_length=9)),
                ('date_draft', models.DateField()),
                ('amt_draft', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('live', 'live'), ('cancelled', 'cancelled')], default='live', max_length=9)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellercounter.district')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellercounter.province')),
            ],
        ),
        migrations.CreateModel(
            name='ChequeContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('mode_donation', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Draft', 'Draft'), ('Kind', 'Kind')], max_length=10)),
                ('cheque_no', models.CharField(max_length=6)),
                ('date_cheque', models.DateField()),
                ('micr_cheque', models.CharField(max_length=9)),
                ('amt_cheque', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('live', 'live'), ('cancelled', 'cancelled')], default='live', max_length=9)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellercounter.district')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellercounter.province')),
            ],
        ),
        migrations.CreateModel(
            name='CashContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('mode_donation', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Draft', 'Draft'), ('Kind', 'Kind')], max_length=10)),
                ('amt_cash', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('live', 'live'), ('cancelled', 'cancelled')], default='live', max_length=9)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellercounter.district')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tellercounter.province')),
            ],
        ),
    ]
