# Generated by Django 3.2.7 on 2022-01-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellercounter', '0003_auto_20220125_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellercounter',
            name='mode_donation',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Draft', 'Draft'), ('Kind', 'Kind')], max_length=10),
        ),
    ]
