# Generated by Django 3.2 on 2023-08-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellercounter', '0004_auto_20230825_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellercounter',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
