# Generated by Django 3.2.7 on 2022-01-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellercounter', '0004_alter_tellercounter_mode_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellercounter',
            name='kind_type',
            field=models.CharField(blank=True, choices=[('Silver Like Material', 'Silver Like Material'), ('Gold Like Material', 'Gold Like Material'), ('Other', 'Other Valueble')], max_length=20, null=True),
        ),
    ]
